import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    // 'Region': [
    //     {
    //         type: 'autogenerated',
    //         dirName: 'region'
    //     }
    // ]
};

export default sidebars;
